#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any
from urllib import error, request


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload a normalized ClawLockRank payload to the configured Worker.",
    )
    parser.add_argument("--input", required=True, help="Path to the payload JSON generated by run_scan.py.")
    parser.add_argument(
        "--api-base",
        default=os.environ.get("CLAWLOCK_RANK_API_BASE", ""),
        help="Worker origin, for example https://clawlock-rank.example.workers.dev",
    )
    parser.add_argument("--nickname", default="", help="Optional nickname override.")
    parser.add_argument("--timeout", type=int, default=15, help="Upload timeout in seconds.")
    parser.add_argument("--yes", action="store_true", help="Skip the interactive upload confirmation prompt.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    api_base = normalize_api_base(args.api_base)
    if not api_base:
        raise SystemExit("Missing Worker origin. Pass --api-base or set CLAWLOCK_RANK_API_BASE.")

    payload_path = Path(args.input).expanduser().resolve()
    if not payload_path.is_file():
        raise SystemExit(f"Payload file not found: {payload_path}")

    try:
        payload = json.loads(payload_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Input file is not valid JSON: {exc}") from exc
    if not isinstance(payload, dict) or not isinstance(payload.get("submission"), dict):
        raise SystemExit("Input file does not contain a valid submission payload.")

    submission = payload["submission"]
    nickname = (args.nickname or str(submission.get("nickname") or "")).strip() or "Anonymous"
    submission["nickname"] = nickname[:24]

    if not args.yes:
        confirm = input(f"Upload score {submission.get('score')} for {submission['nickname']}? [y/N]: ").strip().lower()
        if confirm not in {"y", "yes"}:
            print(json.dumps({"ok": False, "accepted": False, "message": "Upload cancelled."}, indent=2))
            return 0

    endpoint = f"{api_base}/api/submit"
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    http_request = request.Request(
        endpoint,
        data=body,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )

    try:
        with request.urlopen(http_request, timeout=args.timeout) as response:
            raw = response.read().decode("utf-8")
            parsed = json.loads(raw) if raw else {}
            print(json.dumps(parsed, ensure_ascii=False, indent=2))
            return 0 if response.status < 400 else 1
    except error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        parsed = try_parse_json(raw)
        if parsed is None:
            parsed = {"ok": False, "error": raw or f"HTTP {exc.code}"}
        print(json.dumps(parsed, ensure_ascii=False, indent=2), file=sys.stderr)
        return 1
    except error.URLError as exc:
        raise SystemExit(f"Upload failed: {exc.reason}") from exc


def normalize_api_base(value: str) -> str:
    return value.strip().rstrip("/")


def try_parse_json(raw: str) -> dict[str, Any] | None:
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


if __name__ == "__main__":
    sys.exit(main())
